Importando tabela
```{r}
dados <- read.csv("R/tempo.csv", sep = ";", na.strings = "",
stringsAsFactors = TRUE)
head(dados)
summary(dados)
```
Explorando dados, Aparência
Teste para quando os dados são strings
```{r}
counts <- table(dados$Aparencia)
counts
barplot(counts, main = "Aparencia", xlab = "Aparencia")

counts <- table(dados$Vento)
counts
barplot(counts, main = "Vento", xlab = "Vento")

counts <- table(dados$Jogar)
counts
barplot(counts, main = "Jogar", xlab = "Jogar")
```
Explorar, colunas numéricas
```{r}
#Temp
summary(dados$Temperatura)
boxplot(dados$Temperatura)
hist(dados$Temperatura)

#Umidade
summary(dados$Umidade)
boxplot(dados$Umidade)
hist(dados$Umidade)
```
Encontrando valores NAs
```{r}
dados[!complete.cases(dados), ]
```
Coluna Aparência - tratando dominio
```{r}
summary(dados$Aparencia)
#Conferindo NAs
dados[is.na(dados$Aparencia), ]
#Variáveis utilizadas: sol, nublado e chuva
#removendo var menos
dados[dados$Aparencia == "menos", ]$Aparencia <- "sol"
summary(dados$Aparencia)
#Removendo levels não utilizados
dados$Aparencia <- factor(dados$Aparencia)
summary(dados$Aparencia)
```
Coluna Temperatura - tratando dominio
```{r}
summary(dados$Temperatura)
#Conferindo dominio
dados[dados$Temperatura < -130 | dados$Temperatura > 130, ]$Temperatura
#Conferindo NAs
dados[is.na(dados$Temperatura), ]
#Preenchendo valor fora do dominio pela mediana
median(dados$Temperatura)
#Substituindo
dados[dados$Temperatura < -130 | dados$Temperatura > 130, ]$Temperatura <- median(dados$Temperatura) # nolint
#Conferindo
dados[dados$Temperatura < -130 | dados$Temperatura > 130, ]$Temperatura
summary(dados$Temperatura)
```
Coluna Umidade - tratando dominio e NAs
```{r}
summary(dados$Umidade)
#Conferindo dominio
dados[dados$Umidade < 0 | dados$Umidade > 100, ]$Umidade
#Verificando NAs
dados[is.na(dados$Umidade), ]
#Atribuindo mediana ao valor de NA
median(dados$Umidade, na.rm = TRUE)
dados[is.na(dados$Umidade), ]$Umidade <- median(dados$Umidade, na.rm = TRUE)
#Substituindo
dados[dados$Umidade < 0 | dados$Umidade > 100, ]$Umidade <- median(dados$Umidade) # nolint
#Conferindo
dados[dados$Umidade < 0 | dados$Umidade > 100, ]$Umidade
summary(dados$Umidade)
```
Coluna Vento - substituindo NAs
```{r}
summary(dados$Vento)
#Conferindo NAs
dados[is.na(dados$Vento), ]
#Substituindo
dados[is.na(dados$Vento), ]$Vento <- "FALSO"
#Verificando novamente
dados[is.na(dados$Vento), ]

summary(dados$Vento)
```
