```{r}
# Importa dados, string vazio como NA, string como fatores
dados <- read.csv("R/Churn.csv", sep = ";", na.strings = "", stringsAsFactors = T ) # nolint
head(dados)
summary(dados)
```
Colunas
```{r}
#Dar nomes corretos as colunas
colnames(dados) <- c("Id", "Score", "Estado", "Genero", "Idade",
"Patrimonio", "Saldo", "Produtos", "TemCartCredito", "Ativo",
"Salario", "Saiu")
head(dados)
```
Explorar Dados, colunas categóricas
```{r}
#Estados
counts <- table(dados$Estado)
barplot(counts, main = "Estados", xlab = "Estados")

#Gênero
counts <- table(dados$Genero)
barplot(counts, main = "Gêneros", xlab = "Gêneros")
```
Explorar, colunas numéricas
```{r}
summary(dados$Score)
boxplot(dados$Score)
hist(dados$Score)
```
Idade
```{r}
summary(dados$Idade)
boxplot(dados$Idade)
hist(dados$Idade)
```
Saldo
```{r}
summary(dados$Saldo)
boxplot(dados$Saldo)
hist(dados$Saldo)
```
Salário
```{r}
summary(dados$Salario)
boxplot(dados$Salario)
boxplot(dados$Salario, outline = F) # nolint
```
Valores faltantes - NAs
```{r}
dados[!complete.cases(dados), ]
```
Salários
```{r}
#Tratando salários
summary(dados$Salario)
#Vendo a mediana
median(dados$Salario, na.rm = TRUE)
#Atrinbuindo mediana a NAs
dados[is.na(dados$Salario), ]$Salario <- median(dados$Salario, na.rm = TRUE)
#Buscar NAs em salario para checar
dados[!complete.cases(dados$Salario)]
```
Falta de padronização em Gênero
```{r}
#Vendo valores
unique(dados$Genero)
summary(dados$Genero)
#Transformando F e Fem em Feminino
# e M em Masculino
dados[is.na(dados$Genero) | dados$Genero == "M", ]$Genero <- "Masculino"
dados[dados$Genero == "F" | dados$Genero == "Fem", ]$Genero <- "Feminino"
#Vendo resultados
summary(dados$Genero)
#Removendo levels não utilizados
dados$Genero <- factor(dados$Genero)
#Visualizando novamente
summary(dados$Genero)
```
Idades fora do domínio
```{r}
summary(dados$Idade)
#Fora do domínio, numérico - conferindo idades anormais
dados[dados$Idade < 0 | dados$Idade > 110, ]$Idade
#Não tem idades NAs
dados[is.na(dados$Idade), ]
#Opção, preencher com o valor da mediana 
median(dados$Idade)
#Substituindo
dados[dados$Idade < 0 | dados$Idade > 110, ]$Idade <- median(dados$Idade)
#Procurando novamente por dados fora do padrão
dados[dados$Idade < 0 | dados$Idade > 110, ]
summary(dados$Idade)
```
Dados duplicados
```{r}
#Buscando valores duplicados pelo ID
x <- dados[duplicated(dados$Id), ]
x
#Verificamos que o ID 81 está duplicado
#Vamos excluir pelo ID não pelo indice
dados <- dados[!dados$Id %in% c(x$Id), ]
#Buscamos a linha que estava duplicada
dados[dados$Id == x$Id, ]
#Verificamos novamente os valores duplicados
x <- dados[duplicated(dados$Id), ]
x
```
Estado fora do domínio
```{r}
#Fora do dominio - Categorico
unique(dados$Estado)
summary(dados$Estado)
#Preenchendo com moda, RS
dados[!dados$Estado %in% c("RS", "SC", "PR"), ]$Estado <- "RS"
summary(dados$Estado)
#Removendo fatores não usados
dados$Estado <- factor(dados$Estado)
#Visualizando novamente
summary(dados$Estado)
```
Outliers
```{r}
#Outliers, criando um parametro com desvio padrão
desv <- sd(dados$Salario, na.rm = TRUE)
desv
dados[dados$Salario >= 2 * desv, ]$Salario
#Outra forma, resultado semelhante, mas sem os NAs
boxplot(dados$Salario)
boxplot(dados$Salario, outline = FALSE)
x <- boxplot(dados$Salario)$out
x
#Atualizamos todos para mediana
median(dados$Salario)
dados[dados$Salario >= 2 * desv, ]$Salario <- median(dados$Salario)
#Checando se sairam os outliers
dados[dados$Salario >= 2 * desv, ]$Salario
```
