```{r}
library(lattice)
```

Boxplot
```{r}
trees
bwplot(trees$Volume)
bwplot(
  trees$Volume,
  main = "Árvores",
  xlab = "Volume",
)
```

Histograma
```{r}
histogram(trees$Volume, main = "Árvores", xlab = "Volume",
aspect = 1, type = "percent", nint = 20)
```

Histograma condicional
```{r}
chickwts
histogram(chickwts$weight)

aggregate(chickwts$weight, by = list(chickwts$feed), FUN = sum)

histogram(~weight | feed, data = chickwts)
```

Gréfico de dispersão condicional
CO2, seis plantas em dois locais, refrigeradas ou não durante a noite
```{r}
CO2
xyplot(CO2$conc ~ CO2$uptake)
xyplot(CO2$conc ~ CO2$uptake | CO2$Type)
xyplot(CO2$conc ~ CO2$uptake | CO2$Treatment)
```

Cancer de esofago
```{r}
esoph
dotplot(esoph$alcgp ~ esoph$ncontrols, data = esoph)
dotplot(esoph$alcgp ~ esoph$ncontrols | esoph$tobgp)
```

Matriz de dispersão
```{r}
splom(~CO2[4:5] | CO2$Type, CO2)
```

Densidade condicional
```{r}
densityplot(~CO2$conc | CO2$Treatment, plot.points = FALSE)
densityplot(CO2$conc)
densityplot(~CO2$conc | CO2$Treatment)
densityplot(~CO2$conc | CO2$Treatment, plot.points = FALSE)
```

Gráfico 3D
Spray para repelir abelhas
```{r}
OrchardSprays
cloud(decrease ~ rowpos * colpos, data = OrchardSprays)
cloud(decrease ~ rowpos * colpos, groups = treatment, data = OrchardSprays)
```

Level plot
```{r}
trees
levelplot(Girth ~ Height * Volume, data = trees)
```